### ISSUE TITLE
Error install augpy

### ISSUE THREAD

**Issue by BeeFriedman** [itssmutnuri/AugPy#1]
Hi, i tried installing augpy using 
`pip install augpy`
and i get the following error
`C:\Users\barry\Downloads\augpy-1.0.0a1\dist\augpy-1.0.0a1\augpy-1.0.0a1>python setup.py
Traceback (most recent call last):
  File "C:\Users\barry\Downloads\augpy-1.0.0a1\dist\augpy-1.0.0a1\augpy-1.0.0a1\setup.py", line 13, in <module>
    from generate_saturate_cast_cuh import generate_saturate_cast_cuh
ModuleNotFoundError: No module named 'generate_saturate_cast_cuh'`
Could somebody please help me out.

**Comment by itssmutnuri** [comment]
Hi, @CForce99.

Looks like you have the wrong project. This repo is not yet accessible via pip. 

Is this the one you are looking for? 

[https://pypi.org/project/augpy/](https://pypi.org/project/augpy/)
[https://gitlab.com/jfolz/augpy](https://gitlab.com/jfolz/augpy)

**Comment by itssmutnuri** [comment]
If you're looking to use this repo, [the README](https://github.com/itssmutnuri/AugPy#usage) could be of help :)

**Comment by BeeFriedman** [comment]
Oh i am sorry!
